--create table hubernate_sequence (
--        next_val bigint
--) engine = MyISAM;
--
--insert into hubernate_sequence values ( 1 );
--insert into hubernate_sequence values ( 1 );
--
--CREATE TABLE IF NOT EXISTS `taskdb`.`stations` (
--   name VARCHAR(20) not null
--) ENGINE = MyISAM;
--alter table stations add constraint GRAPH primary key (name);
--
--
--
--CREATE TABLE IF NOT EXISTS `taskdb`.`roads` (
--    stations1 VARCHAR(20) not null,
--    stations2 VARCHAR(20) not null,
--    leght INT not null
--) ENGINE = MyISAM;
--
--alter table `roads` add constraint roads_stations1_fk foreign key (stations1) references stations (name);
--alter table `roads` add constraint roads_stations2_fk foreign key (stations2) references stations (name);
--alter table `roads` add constraint circle check (stations1 <> stations2);
--
--CREATE TABLE IF NOT EXISTS `taskdb`.`dijkstra`(
--  stations VARCHAR(20) not null,
--  leght INT not null
--)ENGINE = MyISAM;
--
--alter table dijkstra add constraint dijkstra_pk primary key (stations);
--alter table dijkstra add constraint dijkstra_FK foreign key (stations) references graph_nodes (name);
--
--
--insert into stations (name) values ('А');
--insert into stations (name) values ('Б');
--insert into stations (name) values ('В');
--insert into stations (name) values ('Г');
--insert into stations (name) values ('Д');
--
--insert into stations (name) values ('Е');
--insert into stations (name) values ('Ж');
--insert into stations (name) values ('З');
--insert into stations (name) values ('И');
--insert into stations (name) values ('К');
--


--insert into roads (lenght) values ('150');
--insert into roads (lenght) values ('60');
--insert into roads (lenght) values ('240');
--insert into roads (lenght) values ('30');
--insert into roads (lenght) values ('100');
--
--insert into roads (lenght) values ('40');
--insert into roads (lenght) values ('140');
--insert into roads (lenght) values ('100');
--insert into roads (lenght) values ('100');
--insert into roads (lenght) values ('130');
--
--insert into roads (lenght) values ('120');


--insert into stations_has_roads  values ('1','1');
--insert into stations_has_roads  values ('1','2');
--insert into stations_has_roads  values ('2','2');
--insert into stations_has_roads  values ('2','3');
--insert into stations_has_roads  values ('3','1');
--insert into stations_has_roads  values ('3','5');
--insert into stations_has_roads  values ('4','2');
--insert into stations_has_roads  values ('4','4');
--insert into stations_has_roads  values ('5','3');
--insert into stations_has_roads  values ('5','6');
--insert into stations_has_roads  values ('6','4');
--insert into stations_has_roads  values ('6','5');
--insert into stations_has_roads  values ('7','6');
--insert into stations_has_roads  values ('7','7');
--insert into stations_has_roads  values ('8','5');
--insert into stations_has_roads  values ('8','7');
--insert into stations_has_roads  values ('9','9');
--insert into stations_has_roads  values ('9','7');
--insert into stations_has_roads  values ('10','8');
--insert into stations_has_roads  values ('10','7');
--insert into stations_has_roads  values ('11','10');
--insert into stations_has_roads  values ('11','9');