--create table hubernate_sequence (
--        next_val bigint
--) engine = MyISAM;
--
--insert into hubernate_sequence values ( 1 );
--insert into hubernate_sequence values ( 1 );
--
--CREATE TABLE IF NOT EXISTS `taskdb`.`stations` (
--  `id` INT NULL AUTO_INCREMENT,
--  `name` VARCHAR(45) NOT NULL,
--  PRIMARY KEY (`id`))
--ENGINE = MyISAM;
--
--CREATE TABLE IF NOT EXISTS `taskdb`.`roads` (
--  `id` INT NULL AUTO_INCREMENT,
--  `lenght` INT NOT NULL,
--  PRIMARY KEY (`id`))
--ENGINE = MyISAM;
--
--CREATE TABLE IF NOT EXISTS `taskdb`.`stations_has_roads` (
--  `stations_id` INT NOT NULL,
--  `roads_id` INT NOT NULL,
--  PRIMARY KEY (`stations_id`, `roads_id`),
--  INDEX `fk_stations_has_roads_roads1_idx` (`roads_id` ASC) VISIBLE,
--  INDEX `fk_stations_has_roads_stations_idx` (`stations_id` ASC) VISIBLE,
--  CONSTRAINT `fk_stations_has_roads_stations`
--    FOREIGN KEY (`stations_id`)
--    REFERENCES `taskdb`.`stations` (`id`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION,
--  CONSTRAINT `fk_stations_has_roads_roads1`
--    FOREIGN KEY (`roads_id`)
--    REFERENCES `taskdb`.`roads` (`id`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION)
--ENGINE = MyISAM;
